// Copyright (c) 2025, Sahayog and contributors
// For license information, please see license.txt
/* eslint-disable */

frappe.query_reports["My Audits Report"] = {
	filters: [
		{
			fieldname: "from_date",
			label: __("From Date"),
			fieldtype: "Date",
		},
		{
			fieldname: "to_date",
			label: __("To Date"),
			fieldtype: "Date",
		},
		{
			fieldname: "emp_branch",
			label: __("Branch"),
			fieldtype: "Link",
			options: "Audit Level",
		},
		{
			fieldname: "query_generated_by_empid",
			label: __("Generated By Employee"),
			fieldtype: "Link",
			options: "Employee",
		},
		{
			fieldname: "query_type",
			label: __("Query Type"),
			fieldtype: "Link",
			options: "Audit Query Type",
		},
		{
			fieldname: "status",
			label: __("Query Status"),
			fieldtype: "Select",
			options: "\nDraft\nPending\nClosed",
		},
		{
			fieldname: "stage_name",
			label: __("Audit Stage"),
			fieldtype: "Link",
			options: "Audit Stage",
		},
		{
			fieldname: "stage_status",
			label: __("Stage Response Status"),
			fieldtype: "Select",
			options: "\nPending\nResponded\nNo response\nSkipped",
		},
		{
			fieldname: "stage_employee",
			label: __("Stage Employee"),
			fieldtype: "Link",
			options: "Employee",
		},
	],

	onload: function (report) {
		report.page.add_inner_button(__("Clear Filters"), function () {
			report.filters.forEach((f) => f.set_value(""));
			report.refresh();
		});
	},
};
