import frappe
from frappe.utils import formatdate
from audit_management.audit_management.doctype.my_audits.my_audits import (
    get_user_allowed_divisions, 
    get_user_allowed_sol_ids
)

def execute(filters=None):
    columns = get_columns()
    data = get_data(filters)
    return columns, data

def get_columns():
    columns = [
        {"label": "ID", "fieldname": "name", "fieldtype": "Link", "options": "My Audits", "width": 120},
        {"label": "Date", "fieldname": "date_formatted", "fieldtype": "Data", "width": 100},
        {"label": "Branch", "fieldname": "emp_branch", "fieldtype": "Link", "options": "Audit Level", "width": 100},
        {"label": "Generated By Emp ID", "fieldname": "query_generated_by_empid", "fieldtype": "Link", "options": "Employee", "width": 130},
        {"label": "Generated By Name", "fieldname": "query_generated_by_name", "fieldtype": "Link", "options": "Employee", "width": 150},
        {"label": "Query Type", "fieldname": "query_type", "fieldtype": "Select", "width": 130},
        {"label": "Query Status", "fieldname": "status", "fieldtype": "Select", "width": 130},
        {"label": "Subject", "fieldname": "audit_query_subject_box", "fieldtype": "Data", "width": 200},
        {"label": "Description", "fieldname": "audit_query_box", "fieldtype": "Data", "width": 300},
    ]

    # Fetch all audit stages to add dynamic columns
    stages = frappe.get_all("Audit Stage", order_by="creation asc")
    for s in stages:
        stage_name = s.name
        prefix = stage_name.lower().replace(" ", "_").replace("(", "").replace(")", "").replace("/", "_")
        
        columns.extend([
            {"label": f"{stage_name} Name", "fieldname": f"{prefix}_name", "fieldtype": "Data", "width": 120},
            {"label": f"{stage_name} Response", "fieldname": f"{prefix}_response", "fieldtype": "Data", "width": 180},
            {"label": f"{stage_name} Status", "fieldname": f"{prefix}_status", "fieldtype": "Data", "width": 100}
        ])

    return columns

def get_data(filters):
    # Base query filters
    conditions = ["1=1"]
    params = {}
    
    # 1. Standard Filters
    if filters.get("emp_branch"):
        conditions.append("ma.emp_branch = %(emp_branch)s")
        params["emp_branch"] = filters.emp_branch
        
    if filters.get("query_generated_by_empid"):
        conditions.append("ma.query_generated_by_empid = %(emp_id)s")
        params["emp_id"] = filters.query_generated_by_empid
        
    if filters.get("query_type"):
        conditions.append("ma.query_type = %(q_type)s")
        params["q_type"] = filters.query_type
        
    if filters.get("status"):
        conditions.append("ma.status = %(status)s")
        params["status"] = filters.status
        
    # 2. Dynamic Child Table Filters (via JOIN)
    stage_conditions = []
    if filters.get("stage_name"):
        stage_conditions.append("ai.stage_name = %(stage_name)s")
        params["stage_name"] = filters.stage_name
        
    if filters.get("stage_status"):
        stage_conditions.append("ai.status = %(stage_status)s")
        params["stage_status"] = filters.stage_status
        
    if filters.get("stage_employee"):
        stage_conditions.append("ai.employee = %(stage_employee)s")
        params["stage_employee"] = filters.stage_employee

    if stage_conditions:
        conditions.append(f"EXISTS (SELECT 1 FROM `tabAudit Items` ai WHERE ai.parent = ma.name AND {' AND '.join(stage_conditions)})")

    # 3. Permissions
    user = frappe.session.user
    if "Audit Manager" not in frappe.get_roles(user):
        allowed_sol_ids = get_user_allowed_sol_ids(user)
        if allowed_sol_ids:
            sol_list = ", ".join([frappe.db.escape(str(s)) for s in allowed_sol_ids])
            conditions.append(f"ma.emp_branch IN (SELECT name FROM `tabAudit Level` WHERE sahayog_branch IN ({sol_list}))")
        else:
            conditions.append("ma.owner = %(user)s")
            params["user"] = user

    where_clause = "WHERE " + " AND ".join(conditions)

    query = f"""
        SELECT
            ma.name, ma.creation, ma.status,
            ma.emp_branch, ma.query_generated_by_empid, ma.query_generated_by_name, ma.query_type,
            ma.audit_query_subject_box, ma.audit_query_box
        FROM `tabMy Audits` ma
        {where_clause}
        ORDER BY ma.creation DESC
    """

    result = frappe.db.sql(query, params, as_dict=True)
    
    if not result:
        return []

    parent_names = [r.name for r in result]
    items = frappe.get_all(
        "Audit Items",
        filters={"parent": ["in", parent_names]},
        fields=["parent", "stage_name", "employee_name", "response", "status"]
    )

    items_map = {}
    for it in items:
        if it.parent not in items_map:
            items_map[it.parent] = {}
        
        prefix = it.stage_name.lower().replace(" ", "_").replace("(", "").replace(")", "").replace("/", "_")
        items_map[it.parent][f"{prefix}_name"] = it.employee_name
        items_map[it.parent][f"{prefix}_response"] = it.response
        items_map[it.parent][f"{prefix}_status"] = it.status

    for row in result:
        row["date_formatted"] = formatdate(row.creation, "dd-mm-yyyy")
        if row.name in items_map:
            row.update(items_map[row.name])

    return result
