import frappe
from frappe.utils import formatdate
from audit_management.audit_management.doctype.my_audits.my_audits import (
    get_user_allowed_divisions, 
    get_user_allowed_sol_ids
)


def execute(filters=None):
    columns = get_columns()
    data = get_data(filters)
    return columns, data


def get_columns():
    return [
        {"label": "ID", "fieldname": "name", "fieldtype": "Link", "options": "My Audits", "width": 120},
        {"label": "Date", "fieldname": "date_formatted", "fieldtype": "Data", "width": 100},
        {"label": "Branch", "fieldname": "emp_branch", "fieldtype": "Link", "options": "Audit Level", "width": 100},
        {"label": "Generated By Emp ID", "fieldname": "query_generated_by_empid", "fieldtype": "Link", "options": "Employee", "width": 130},
        {"label": "Generated By Name", "fieldname": "query_generated_by_name", "fieldtype": "Link", "options": "Employee", "width": 150},
        {"label": "Query Type", "fieldname": "query_type", "fieldtype": "Select", "width": 130},
        {"label": "Query Status", "fieldname": "status", "fieldtype": "Select", "width": 130},
        {"label": "Subject", "fieldname": "audit_query_subject_box", "fieldtype": "Data", "width": 200},
        {"label": "Description", "fieldname": "audit_query_box", "fieldtype": "Data", "width": 300},
        {"label": "BM Name", "fieldname": "bm_name", "fieldtype": "Data", "width": 120},
        {"label": "BM Response", "fieldname": "bm_response_box", "fieldtype": "Data", "width": 180},
        {"label": "DH Name", "fieldname": "dh_name", "fieldtype": "Data", "width": 120},
        {"label": "DH Response", "fieldname": "dh_response_box", "fieldtype": "Data", "width": 180},
        {"label": "COM Name", "fieldname": "com_name", "fieldtype": "Data", "width": 120},
        {"label": "COM Response", "fieldname": "com_response_box", "fieldtype": "Data", "width": 180},
        {"label": "RM Name", "fieldname": "rm_name", "fieldtype": "Data", "width": 120},
        {"label": "RM Response", "fieldname": "rm_response_box", "fieldtype": "Data", "width": 180},
        {"label": "ROM Name", "fieldname": "rom_name", "fieldtype": "Data", "width": 120},
        {"label": "ROM Response", "fieldname": "rom_response_box", "fieldtype": "Data", "width": 180},
        {"label": "ZM Name", "fieldname": "zm_name", "fieldtype": "Data", "width": 120},
        {"label": "ZM Response", "fieldname": "zm_response_box", "fieldtype": "Data", "width": 180},
        {"label": "ZOM Name", "fieldname": "zom_name", "fieldtype": "Data", "width": 120},
        {"label": "ZOM Response", "fieldname": "zom_response_box", "fieldtype": "Data", "width": 180},
        {"label": "GM Name", "fieldname": "gm_name", "fieldtype": "Data", "width": 120},
        {"label": "GM Response", "fieldname": "gm_response_box", "fieldtype": "Data", "width": 180},
        {"label": "HR Name", "fieldname": "hr_name", "fieldtype": "Data", "width": 120},
        {"label": "HR Response", "fieldname": "hr_response_box", "fieldtype": "Data", "width": 180},
        {"label": "COO Name", "fieldname": "coo_name", "fieldtype": "Data", "width": 120},
        {"label": "COO Response", "fieldname": "coo_response_box", "fieldtype": "Data", "width": 180},
        {"label": "CEO Name", "fieldname": "ceo_name", "fieldtype": "Data", "width": 120},
        {"label": "CEO Response", "fieldname": "ceo_response_box", "fieldtype": "Data", "width": 180},
    ]


def get_data(filters):
    conditions = []
    user = frappe.session.user
    roles = frappe.get_roles(user)

    # ======================
    # ROLE-BASED PERMISSIONS
    # ======================
    
    is_audit_manager = "Audit Manager" in roles or "Administrator" in roles or "System Manager" in roles
    is_audit_member = "Audit Member" in roles
    
    if is_audit_manager:
        # Sees everything, no perm filter needed
        pass
    elif is_audit_member:
    # Audit Member: only own created records
        conditions.append(
            f"owner = {frappe.db.escape(user)}"
        )
    else:
        # Other users: Sol ID based access (from Report Preference) 
        # OR records where they are participants
        allowed_sol_ids = get_user_allowed_sol_ids(user)
        perm_conds = [f"owner = {frappe.db.escape(user)}"]
        
        if allowed_sol_ids:
            sol_list = ", ".join([frappe.db.escape(str(s)) for s in allowed_sol_ids])
            perm_conds.append(f"""
                (
                    status != 'Draft'
                    AND
                    emp_branch IN (
                        SELECT name FROM `tabAudit Level`
                        WHERE sahayog_branch IN ({sol_list})
                    )
                )
            """)
            
        # Also include where they are assigned (Audit Items)
        perm_conds.append(f"""
            (
                status != 'Draft'
                AND EXISTS (
                    SELECT name
                    FROM `tabAudit Items`
                    WHERE parent = `tabMy Audits`.name
                    AND (
                        user_id = {frappe.db.escape(user)}
                        OR email = {frappe.db.escape(user)}
                    )
                )
            )
        """)
        
        conditions.append(f"({' OR '.join(perm_conds)})")

    # ======================
    # UI FILTERS
    # ======================
    if filters.get("emp_branch"):
        conditions.append(f"emp_branch = {frappe.db.escape(filters.emp_branch)}")

    if filters.get("query_generated_by_empid"):
        conditions.append(f"query_generated_by_empid = {frappe.db.escape(filters.query_generated_by_empid)}")

    if filters.get("query_type"):
        conditions.append(f"query_type = {frappe.db.escape(filters.query_type)}")

    if filters.get("status"):
        conditions.append(f"status = {frappe.db.escape(filters.status)}")

    for level in ["bm", "dh", "com", "rm", "rom", "zm", "zom", "gm", "hr", "coo", "ceo"]:
        if filters.get(f"{level}_user_status"):
            status = filters.get(f"{level}_user_status")
            if status == "Responded":
                conditions.append(f"{level}_response_box IS NOT NULL AND {level}_response_box != ''")
            elif status == "No response":
                conditions.append(f"({level}_response_box IS NULL OR {level}_response_box = '')")

    if filters.get("from_date"):
        conditions.append(f"DATE(creation) >= {frappe.db.escape(filters.from_date)}")

    if filters.get("to_date"):
        conditions.append(f"DATE(creation) <= {frappe.db.escape(filters.to_date)}")

    where_clause = f"WHERE {' AND '.join(conditions)}" if conditions else ""

    query = f"""
        SELECT
            name, creation, status,
            emp_branch, query_generated_by_empid, query_generated_by_name, query_type,
            audit_query_subject_box, audit_query_box,
            bm_name, bm_response_box,
            dh_name, dh_response_box,
            com_name, com_response_box,
            rm_name, rm_response_box,
            rom_name, rom_response_box,
            zm_name, zm_response_box,
            zom_name, zom_response_box,
            gm_name, gm_response_box,
            hr_name, hr_response_box,
            coo_name, coo_response_box,
            ceo_name, ceo_response_box
        FROM `tabMy Audits`
        {where_clause}
        ORDER BY creation DESC
    """

    result = frappe.db.sql(query, as_dict=True)

    for row in result:
        row["date_formatted"] = formatdate(row.creation, "dd-mm-yyyy")

    return result
