// Copyright (c) 2025, Sahayog and contributors
// For license information, please see license.txt
/* eslint-disable */

frappe.query_reports["My Audits Report"] = {
  filters: [
    {
      fieldname: "from_date",
      label: "From Date",
      fieldtype: "Date",
    },
    {
      fieldname: "to_date",
      label: "To Date",
      fieldtype: "Date",
    },
    {
      fieldname: "emp_branch",
      label: "Branch",
      fieldtype: "Link",
      options: "Audit Level",
    },
    {
      fieldname: "query_generated_by_empid",
      label: "Generated By (Emp ID)",
      fieldtype: "Link",
      options: "Employee",
      get_query: () => {
        return {
          filters: {
            status: "Active",
            department: "Audit",
          },
        };
      },
    },
    {
      fieldname: "query_generated_by_name",
      label: "Generated By (Name)",
      fieldtype: "Link",
      options: "Employee",
      get_query: () => {
        return {
          filters: {
            status: "Active",
            department: "Audit",
          },
        };
      },
    },
    {
      fieldname: "query_type",
      label: "Query Type",
      fieldtype: "Select",
      options: "\nAudit Report Compliance\nCritical Compliance",
    },
    {
      fieldname: "status",
      label: "Query Status",
      fieldtype: "Select",
      options: "\nDraft\nPending\nClosed",
    },
    {
      fieldname: "bm_user_status",
      label: "BM Response Status",
      fieldtype: "Select",
      options: "\nResponded\nNo response",
    },
    {
      fieldname: "dh_user_status",
      label: "DH Response Status",
      fieldtype: "Select",
      options: "\nResponded\nNo response",
    },
    {
      fieldname: "com_user_status",
      label: "COM Response Status",
      fieldtype: "Select",
      options: "\nResponded\nNo response",
    },
    {
      fieldname: "rm_user_status",
      label: "RM Response Status",
      fieldtype: "Select",
      options: "\nResponded\nNo response",
    },
    {
      fieldname: "rom_user_status",
      label: "ROM Response Status",
      fieldtype: "Select",
      options: "\nResponded\nNo response",
    },
    {
      fieldname: "zm_user_status",
      label: "ZM Response Status",
      fieldtype: "Select",
      options: "\nResponded\nNo response",
    },
    {
      fieldname: "zom_user_status",
      label: "ZOM Response Status",
      fieldtype: "Select",
      options: "\nResponded\nNo response",
    },
    {
      fieldname: "gm_user_status",
      label: "GM Response Status",
      fieldtype: "Select",
      options: "\nResponded\nNo response",
    },
    {
      fieldname: "hr_user_status",
      label: "HR Response Status",
      fieldtype: "Select",
      options: "\nResponded\nNo response",
    },
    {
      fieldname: "coo_user_status",
      label: "COO Response Status",
      fieldtype: "Select",
      options: "\nResponded\nNo response",
    },
    {
      fieldname: "ceo_user_status",
      label: "CEO Response Status",
      fieldtype: "Select",
      options: "\nResponded\nNo response",
    },
  ],

  // clear filters button
  onload: function (report) {
    report.page.add_inner_button(__("Clear Filters"), function () {
      report.filters.forEach((f) => f.set_value(""));
      report.refresh();
    });
  },
};
